name: Race Condition Test

on:
  push:
    branches:
      - race_condition_test

jobs:
  noop:
    name: No op
    runs-on: ubuntu-latest
    steps:

    - name: Sleep 1 second
      run: |
        sleep 1s
